version: '3'
services:
  web:
    build: .
    image: shaybix/weather-monster:1.0
    ports:
    - "3000:3000"
    depends_on:
    - "db" 
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: "weather"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"